### ISSUE TITLE
AnyLoc

### ISSUE THREAD

**Issue by aleshem** [gmberton/VPR-methods-evaluation#2]
Hi have you compared your results to AnyLoc?
https://github.com/AnyLoc/AnyLoc
It would be interesting to test the performance as they claim to have very high performance https://paperswithcode.com/task/visual-place-recognition/latest

**Comment by gmberton** [comment]
Great question, I'm actually planning to add AnyLoc to this codebase, and then it will be much easier to run experiments.
My guess is that EigenPlaces wins on all "standard VPR" datasets, like the ones used in the EigenPlaces paper (e.g. on Pitts30k EigenPlaces has R@1=92.5 while AnyLoc has R@1=87.6), but that AnyLoc wins on the more "unusual" VPR domains, like many of the datasets in the AnyLoc paper (like Hawkins, Laurel Caverns, Nardo-Air).
I'm actually waiting for them to add AnyLoc to torch.hub (see [this issue on their repo](https://github.com/AnyLoc/AnyLoc/issues/11)) and then it will be much easier to add it to this repo.

**Comment by aleshem** [comment]
Great answer thanks
