### ISSUE TITLE
Ask some queestion for match

### ISSUE THREAD

**Issue by ionLi** [gmberton/VPR-methods-evaluation#3]
Hi, I am a student of University of Chinese Academy of Sciences ，this is a good framework for VPR;
I have a question about image matching between these different methods, in this experiment faiss was used for prediction but I want to use some of our own collected data for querying, some of the coordinate formats they have are not the same as the open source data format
So I would like to know **whether all of these different methods are doing** **matching by multiplying the query image and the db image vectors to find the maximal vector product to find the top image**
Thanks

**Comment by gmberton** [comment]
Hi, all methods do inference in the same way: the features extracted from the query is compared to the features from the database, and the most similar one from the database is found through a kNN. I hope this answer your question

**Comment by ionLi** [comment]
ok,thanks your answer,I have solved this problem
