### ISSUE TITLE
The questions about Anyloc's output

### ISSUE THREAD

**Issue by BinuxLiu** [gmberton/VPR-methods-evaluation#5]
AnyLoc's desc dim is set to 49152.
However, I noticed that the log message printed:
```
VLAD caching is disabled.
Desc dim set to 1536
```
Does this affect experimental evaluation?

**Comment by BinuxLiu** [comment]
I looked at the source code of AnyLoc.
These are probably the initialization parameters required by VLAD during training and do not affect testing.

**Comment by gmberton** [comment]
I agree, and that is a message from AnyLoc's code that can't be removed from this repo.
I agree that it's a bit confusing within this codebase though
