### ISSUE TITLE
Issue with Low Performance of MixVPR on msls_val Evaluation

### ISSUE THREAD

**Issue by SeunghanYu** [gmberton/VPR-methods-evaluation#7]
Hello, @gmberton!

I am trying to measure the **msls_val** performance using the following code.
The backbone is **ResNet50** and the method is **MixVPR**.

```
python3 main.py \
--database_folder=../VPR-datasets-downloader/datasets/msls/images/val/database \
--queries_folder=../VPR-datasets-downloader/datasets/msls/images/val/queries \
--method=mixvpr \
--backbone=ResNet50 \
--descriptors_dimension=512
```

However, I encountered an error due to an image size issue. To resolve this, I used the following command:

```
python3 main.py \
--database_folder=../VPR-datasets-downloader/datasets/msls/images/val/database \
--queries_folder=../VPR-datasets-downloader/datasets/msls/images/val/queries \
--method=mixvpr \
--backbone=ResNet50 \
--descriptors_dimension=512 \
--image_size 480 640
```

This resolved the error, but the performance results were significantly lower compared to other results with the same conditions.

```
2024-06-03 04:17:33   Testing with mixvpr with a ResNet50 backbone and descriptors dimension 512
2024-06-03 04:17:33   The outputs are being saved in logs/default/2024-06-03_04-17-33
Searching test images in /mnt/hdd2/VPR-datasets-downloader/datasets/msls/images/test/database with glob()
Searching test images in /mnt/hdd2/VPR-datasets-downloader/datasets/msls/images/test/queries with glob()
2024-06-03 04:17:35   Testing on < #queries: 11084; #database: 18871 >
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4718/4718 [04:05<00:00, 19.19it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11084/11084 [02:34<00:00, 71.71it/s]
2024-06-03 04:24:16   R@1: 79.8, R@5: 88.4, R@10: 90.6, R@20: 92.5
```

Compared to the results on the [MixVPR GitHub](https://github.com/amaralibey/MixVPR):

    R@1: 84.1
    R@5: 91.8
    R@10: 93.7

And the EigenPlaces paper Table 3:

    R@1: 83.6

These results seem to indicate a problem.
Is it not recommended to measure msls_val performance with this VPR-methods-evaluation?

Looking forward to your reply. Thank you in advance!

**Comment by gmberton** [comment]
Hi @SeunghanYu,

this issue is due to an ambiguity of the MSLS val set. Sometimes all 11084 queries are used, while sometimes only 740 are used.
Both in the MixVPR and EigenPlaces papers we're using the 740 queries subset, which leads to better results (you can see proof of this in the EigenPlaces paper Table 1).
I should definitely update the `VPR-datasets-downloader` repo to allow users to also create the MSLS val set with 740, but I doubt I'll find the time any time soon. If you could help with that, it would be great.

Hope this clarifies your doubts!
